import * as fs from 'fs'
import * as path from 'path'

interface FeatureFlags {
  onlineBooking: boolean
  loyaltyProgram: boolean
  smsNotifications: boolean
  whatsappAutomation: boolean
  aiChatbot: boolean
  advancedAnalytics: boolean
  multiLocation: boolean
  inventoryManagement: boolean
}

const DEFAULT_FLAGS: FeatureFlags = {
  onlineBooking: false,
  loyaltyProgram: false,
  smsNotifications: false,
  whatsappAutomation: false,
  aiChatbot: false,
  advancedAnalytics: false,
  multiLocation: false,
  inventoryManagement: false,
}

function loadFeatures(): FeatureFlags {
  // Try loading from features.json first (generated by inject.ts)
  const jsonPath = path.resolve(__dirname, 'features.json')
  if (fs.existsSync(jsonPath)) {
    try {
      const raw = fs.readFileSync(jsonPath, 'utf-8')
      return { ...DEFAULT_FLAGS, ...JSON.parse(raw) }
    } catch {
      // fall through to env vars
    }
  }

  // Fallback to environment variables
  return {
    onlineBooking: process.env.FEATURE_ONLINE_BOOKING === 'true',
    loyaltyProgram: process.env.FEATURE_LOYALTY_PROGRAM === 'true',
    smsNotifications: process.env.FEATURE_SMS_NOTIFICATIONS === 'true',
    whatsappAutomation: process.env.FEATURE_WHATSAPP_AUTOMATION === 'true',
    aiChatbot: process.env.FEATURE_AI_CHATBOT === 'true',
    advancedAnalytics: process.env.FEATURE_ADVANCED_ANALYTICS === 'true',
    multiLocation: process.env.FEATURE_MULTI_LOCATION === 'true',
    inventoryManagement: process.env.FEATURE_INVENTORY_MANAGEMENT === 'true',
  }
}

export const features = loadFeatures()

export function isFeatureEnabled(feature: keyof FeatureFlags): boolean {
  return features[feature] === true
}
